"""initial schema

Revision ID: 052af66b5146
Revises:
Create Date: 2026-08-13 20:17:30.922564

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "052af66b5146"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("symbol_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("relative_path", sa.String(length=2000), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("qualified_name", sa.String(length=1000), nullable=False),
        sa.Column("symbol_kind", sa.String(length=50), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("part_index", sa.Integer(), nullable=False),
        sa.Column("part_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chunks_snapshot_id"), "chunks", ["snapshot_id"], unique=False
    )
    op.create_index(
        op.f("ix_chunks_source_file_id"), "chunks", ["source_file_id"], unique=False
    )
    op.create_index(op.f("ix_chunks_symbol_id"), "chunks", ["symbol_id"], unique=False)
    op.create_table(
        "import_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=1000), nullable=False),
        sa.Column("imported_name", sa.String(length=500), nullable=True),
        sa.Column("alias", sa.String(length=500), nullable=True),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_references_source_file_id"),
        "import_references",
        ["source_file_id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("remote_url", sa.String(length=2000), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repositories_project_id"), "repositories", ["project_id"], unique=False
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=True),
        sa.Column("remote_url", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_snapshots_repository_id"), "snapshots", ["repository_id"], unique=False
    )
    op.create_table(
        "source_file_relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("target_file_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_file_relations_source_file_id"),
        "source_file_relations",
        ["source_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_file_relations_target_file_id"),
        "source_file_relations",
        ["target_file_id"],
        unique=False,
    )
    op.create_table(
        "source_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.String(length=2000), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_files_snapshot_id"),
        "source_files",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "symbol_relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_symbol_id", sa.Uuid(), nullable=False),
        sa.Column("target_symbol_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_symbol_relations_source_symbol_id"),
        "symbol_relations",
        ["source_symbol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_symbol_relations_target_symbol_id"),
        "symbol_relations",
        ["target_symbol_id"],
        unique=False,
    )
    op.create_table(
        "symbols",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("qualified_name", sa.String(length=1000), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("parent_symbol_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_symbols_parent_symbol_id"),
        "symbols",
        ["parent_symbol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_symbols_source_file_id"), "symbols", ["source_file_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_symbols_source_file_id"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_parent_symbol_id"), table_name="symbols")
    op.drop_table("symbols")
    op.drop_index(
        op.f("ix_symbol_relations_target_symbol_id"), table_name="symbol_relations"
    )
    op.drop_index(
        op.f("ix_symbol_relations_source_symbol_id"), table_name="symbol_relations"
    )
    op.drop_table("symbol_relations")
    op.drop_index(op.f("ix_source_files_snapshot_id"), table_name="source_files")
    op.drop_table("source_files")
    op.drop_index(
        op.f("ix_source_file_relations_target_file_id"),
        table_name="source_file_relations",
    )
    op.drop_index(
        op.f("ix_source_file_relations_source_file_id"),
        table_name="source_file_relations",
    )
    op.drop_table("source_file_relations")
    op.drop_index(op.f("ix_snapshots_repository_id"), table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_repositories_project_id"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_table("projects")
    op.drop_index(
        op.f("ix_import_references_source_file_id"), table_name="import_references"
    )
    op.drop_table("import_references")
    op.drop_index(op.f("ix_chunks_symbol_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_source_file_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_snapshot_id"), table_name="chunks")
    op.drop_table("chunks")
    # ### end Alembic commands ###
